export interface CarouselItem {
	image: string;
	order: number;
	id: string;
	width?: string;
	height?: string;
}

export const carouselItems: CarouselItem[] = [
	{
		image: 'assets/images/carousel/vucho_com.webp',
		order: 1,
		id: '1',
		width: '160.563px',
		height: '40px',
	},
	{
		image: 'assets/images/carousel/asgard.webp',
		order: 2,
		id: '2',
		width: '185px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/dubok_logo.webp',
		order: 3,
		id: '3',
		width: '233px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/rikota.webp',
		order: 4,
		id: '4',
		width: '179px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/extra_life.webp',
		order: 5,
		id: '5',
		width: '116px',
		height: '39.904px',
	},
	{
		image: 'assets/images/carousel/dorblu_logo.webp',
		order: 6,
		id: '6',
		width: '98px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/okko.webp',
		order: 7,
		id: '7',
		width: '127px',
		height: '32px',
	},
	{
		image: 'assets/images/carousel/mamash.webp',
		order: 8,
		id: '8',
		width: '184px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/cotnar.webp',
		order: 9,
		id: '9',
		width: '143px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/croissants_logo.webp',
		order: 10,
		id: '10',
		width: '90px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/cafe_rynok.webp',
		order: 11,
		id: '11',
		width: '66px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/avalon.svg',
		order: 12,
		id: '12',
		width: '60px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/duck`s_lake.webp',
		order: 13,
		id: '13',
		width: '123px',
		height: '39.709px',
	},
	{
		image: 'assets/images/carousel/eat_me.webp',
		order: 14,
		id: '14',
		width: '60px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/enzym.webp',
		order: 15,
		id: '15',
		width: '100px',
		height: '36px',
	},
	{
		image: 'assets/images/carousel/bilyi_nalyv_logo.webp',
		order: 16,
		id: '16',
		width: '60px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/fruity_souls_logo.webp',
		order: 17,
		id: '17',
		width: '103px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/galicia.webp',
		order: 18,
		id: '18',
		width: '98px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/grono.webp',
		order: 19,
		id: '19',
		width: '129px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/gs_logo.webp',
		order: 20,
		id: '20',
		width: '68px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/hapai_logo.webp',
		order: 21,
		id: '21',
		width: '105.819px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/HOMEOFARTS_LOGO.webp',
		order: 22,
		id: '22',
		width: '218px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/kit_logo.webp',
		order: 23,
		id: '23',
		width: '78px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/kodi_logo.webp',
		order: 24,
		id: '24',
		width: '135px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/kumpelgroup_logo.webp',
		order: 25,
		id: '25',
		width: '105px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/lviv_bud.webp',
		order: 26,
		id: '26',
		width: '121px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/lviv.webp',
		order: 27,
		id: '27',
		width: '59px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/choco_bum_logo.webp',
		order: 28,
		id: '28',
		width: '60px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/ministerstvo_logo.webp',
		order: 29,
		id: '29',
		width: '124px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/nuts.webp',
		order: 30,
		id: '30',
		width: '111px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/celentano_logo.webp',
		order: 31,
		id: '31',
		width: '131px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/raymond.webp',
		order: 32,
		id: '32',
		width: '106px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/rem_logo.webp',
		order: 33,
		id: '33',
		width: '136px',
		height: '60px',
	},
	{
		image: 'assets/images/carousel/barbercompany.webp',
		order: 34,
		id: '34',
		width: '168px',
		height: '30px',
	},
	{
		image: 'assets/images/carousel/ulf_logo.webp',
		order: 35,
		id: '35',
		width: '117px',
		height: '60px',
	},
];

export const portfolioCarouselItems: CarouselItem[] = [
	{ id: '1', image: '/assets/images/portfolio-carousel/desktop_portfolio_photo_1.webp', order: 1 },
	{ id: '2', image: 'assets/images/portfolio-carousel/desktop_portfolio_photo_2.webp', order: 2 },
	// { id: '3', image: 'assets/images/portfolio-carousel/desktop_portfolio_photo_3.webp', order: 3 },
	// { id: '4', image: 'assets/images/portfolio-carousel/desktop_portfolio_photo_4.webp', order: 4 },
	// { id: '5', image: 'assets/images/portfolio-carousel/desktop_portfolio_photo_5.webp', order: 5 },
];
