# GitHub Actions Workflow for deploying Angular SSR app to Azure Web App

name: Build and deploy Angular SSR app to Azure Web App - submarinefront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build:ssr  # This runs the SSR build script

      - name: Zip artifact for deployment
        run: zip -r release.zip dist/app  # Zips the SSR build directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_41DD9048978948CC8CBCF8A21A291C42 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1DCA504402254862AAC0F7B20915FC90 }}
          subscription-id: '589d70bf-00ff-48a5-9307-5587fb4ca59c'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'submarinefront'
          package: dist/app  # Ensure correct SSR build directory

      - name: Set Startup Command
        run: |
          az webapp config appsettings set --name submarinefront --resource-group submarinefront --settings \
            PORT=8080 \
            STARTUP_COMMAND="npm run serve:ssr:app"
