name: Build and deploy Angular SSR app to Azure Web App - submarine-fe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app for production
        run: npm run build --c=production

      - name: Zip artifact for deployment
        run: zip -r release.zip dist/ # Package the `dist` directory containing the built app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 7fe0de6b-a5ce-4b34-b8a7-0adefaef33d3
          tenant-id: b7253a37-9654-48b4-8cab-60b69cd48967
          subscription-id: 589d70bf-00ff-48a5-9307-5587fb4ca59c

      - name: Deploy SSR app to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'submarine-fe'
          slot-name: 'Production'
          package: dist/ # Deploy the SSR build directory
          startup-command: 'node dist/app/server/server.mjs' # Run the SSR server script
